### ISSUE TITLE
Styles for HTML elements should not be in the addon styles

### ISSUE THREAD

**Issue by kyleshevlin** [shipshapecode/ember-contact-form#3]
Styles for HTML elements such as `html`, `body`, and `a` should not be in the addon as they will potentially conflict with the users styles for these elements. Markup and CSS can be written to avoid these conflicts.

These styles _can_ be in the dummy app styles for the sake of github page, otherwise, we should avoid such global and overreaching styles.

**Comment by rwwagner90** [comment]
Totally agree with you! I'll take a look at moving them

**Comment by kyleshevlin** [comment]
I am also happy to do this now that the sass_refactor branch was merged. Let me know if you want me to tackle it instead.

**Comment by rwwagner90** [comment]
I'm always happy for other people to do work, if you'd like to do it @kyleshevlin. You've just been doing a lot, didn't want to burn you out.

**Comment by kyleshevlin** [comment]
I'll get it then, no worries.

**Comment by rwwagner90** [comment]
Is this resolved after the merge @kyleshevlin?

**Comment by kyleshevlin** [comment]
Yep.
